Make changes from code reviewer
Kajal19-del/To-do-list pull request #3
Opened 2023-02-23 16:55 UTC by Kajal19-del

# In this milestone I did the following activities:
- I setup webpack first
- I add HTML, CSS, and javascript files for the to-do-list project
- I set up a module folder for different JS file
- I add (Add & Remove) task features for this project
- I pass  all the linter errors

2023-02-23 17:15 UTC, Zuhaib042 reviewed
Hi @Kajal19-del , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project for re-review, but you are not submitting the same PR that you have submitted for the first time.
we have to submit the same PR for the re-reviews.
Also this PR only have one file so I cant review it properly using Github features like inline-comments.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-23 18:30 UTC, Kajal19-del commented
The previous pull request was merged by mistake but I put the old PR link below
https://github.com/Kajal19-del/To-do-list/pull/2

2023-02-23 18:59 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @Kajal19-del   :wave: 

Well done. :+1:  
You need to fix some issues before moving to the next project. :running_man: 

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing
✔️ Use GitHub Flow
✔️ Meaningful commit messages.


## Required Changes ♻️

_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 18:59 UTC, Tufahel commented on src/index.html
> +		  <button class="clearAll">Clear all completed</button>
- [ ] You have implemented `Clear All Completed` function in `index.js`. This function is for deleting all selected lists. Now as per the requirement you need to implement another function and button to delete a specific list.

- ***Requirement***
![image](https://user-images.githubusercontent.com/60083437/221003436-2195b0e8-be01-444c-bfe2-5832b5f5c11f.png)

- ***Suggestion on your design***
![image](https://user-images.githubusercontent.com/60083437/221003885-0147cb03-5352-4efe-8274-c1c623d8e120.png)

2023-02-24 09:09 UTC, Shedrack-Sunday approved these changes
Hi @Kajal19-del 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-24 09:24 UTC, merged